#!/bin/bash


export SINGULARITY_BINDPATH="/directflow/SCCGGroupShare/projects/,/data:/mnt"

snakemake --snakefile /directflow/SCCGGroupShare/projects/DrewNeavin/Demultiplex_Benchmark/scripts/ONEK1K/hg38/refSNVs/Snakefile \
    --rerun-incomplete --jobs 74 --use-singularity \
    --cluster "qsub -S /bin/bash -q short.q -r yes -l tmp_requested=200G -l mem_requested=200G -e /directflow/SCCGGroupShare/projects/DrewNeavin/Demultiplex_Benchmark/output/Consortium/logs -o /directflow/SCCGGroupShare/projects/DrewNeavin/Demultiplex_Benchmark/output/Consortium/logs -j y -V"


